# Fixed list of meme templates from IMGflip.

MEME_VARIANTS = [
    {
        "id": "181913649",
        "title": "Drake Hotline Bling",
        "box_count": 2,
        "explanation": "The Drake Hotline Bling meme is funny because of the way Drake dances in the music video. His unique and quirky dance moves have been used to depict different situations or emotions, adding humor to various scenarios. The image of Drake dancing has become a widely recognizable symbol that people use to create playful and relatable memes.",
        "formatting": '2 text captions overlaying the "Drake Hotline Bling" meme.',
    },
    {
        "id": "87743020",
        "title": "Two Buttons",
        "box_count": 3,
        "explanation": "The humor in the Two Buttons meme lies in the dilemma presented by the two options. The buttons typically represent two conflicting choices, with both having negative outcomes. The joke usually arises from the absurdity of the situation or the irony in the decision-making process.",
        "formatting": '3 text captions overlaying the "Two Buttons" meme.',
    },
    {
        "id": "112126428",
        "title": "Distracted Boyfriend",
        "box_count": 3,
        "explanation": "The humor in the Distracted Boyfriend meme comes from the relatable and exaggerated scenario it portrays. The image of a man checking out another woman while his girlfriend looks on disapprovingly strikes a chord with many people, as it humorously depicts a common yet awkward situation. Additionally, the use of the meme template in various creative and unexpected contexts adds an element of surprise and humor to the meme.",
        "formatting": '3 text captions overlaying the "Distracted Boyfriend" meme.',
    },
    {
        "id": "131087935",
        "title": "Running Away Balloon",
        "box_count": 5,
        "explanation": "The Running Away Balloon meme is funny because it combines a mundane, everyday object like a balloon with the concept of running away, which is typically associated with dramatic or urgent situations. The humor comes from the juxtaposition of the ordinary and the extraordinary, creating a humorous and surreal visual image.",
        "formatting": '5 text captions overlaying the "Running Away Balloon" meme.',
    },
    {
        "id": "217743513",
        "title": "UNO Draw 25 Cards",
        "box_count": 2,
        "explanation": "The UNO Draw 25 Cards meme is funny because it exaggerates the consequences of a typical UNO game, where drawing extra cards is a frustrating aspect of the game. The meme plays on this frustration by showing absurdly high numbers of cards being drawn, which is humorous and relatable to anyone who has played UNO.",
        "formatting": '2 text captions overlaying the "UNO Draw 25 Cards" meme.',
    },
    {
        "id": "124822590",
        "title": "Left Exit 12 Off Ramp",
        "box_count": 3,
        "explanation": "The Left Exit 12 Off Ramp meme is funny because it typically involves a situation where the subject has made a decision to deviate from the logical course of action, similar to taking the exit off the highway when not necessary. The meme often highlights moments of confusion, absurdity, or unexpected outcomes, making it humorous for viewers.",
        "formatting": '3 text captions overlaying the "Left Exit 12 Off Ramp" meme.',
    },
    {
        "id": "222403160",
        "title": "Bernie I Am Once Again Asking For Your Support",
        "box_count": 2,
        "explanation": "The humor in this meme comes from the relatability and persistence of Bernie Sanders in seeking support for his cause. The image of him slightly hunched over with a determined expression has been paired with various captions to humorously depict situations where someone is asking for help or support multiple times. It's funny because it captures a common experience of repeatedly seeking assistance or support for something.",
        "formatting": '2 text captions overlaying the "Bernie I Am Once Again Asking For Your Support" meme.',
    },
    {
        "id": "129242436",
        "title": "Change My Mind",
        "box_count": 2,
        "explanation": 'The "Change My Mind" meme typically features a photo of someone sitting at a table with a sign that presents a controversial statement or opinion, inviting others to challenge or debate them. The humor comes from the absurdity of the statement, the idea of someone confidently presenting it, and the potential for creative and witty responses from others.',
        "formatting": '2 text captions overlaying the "Change My Mind" meme.',
    },
    {
        "id": "4087833",
        "title": "Waiting Skeleton",
        "box_count": 2,
        "explanation": "The Waiting Skeleton meme is funny because it humorously depicts an eternal, endless waiting situation. The skeleton's expression conveys the frustration and impatience that we all feel when waiting for something for a long time. It's a humorous way to exaggerate the feeling of waiting for something that seems like it will never happen.",
        "formatting": '2 text captions overlaying the "Waiting Skeleton" meme.',
    },
    {
        "id": "131940431",
        "title": "Gru's Plan",
        "box_count": 4,
        "explanation": 'The humor in the Gru\'s Plan meme comes from the relatability of having a complex plan that is ultimately very simple or mundane. The meme format typically involves Gru from "Despicable Me" presenting a large, elaborate plan that is followed by a much simpler or ridiculous solution. This contrast between the grand plan and its underwhelming execution is what makes the meme humorous to many.',
        "formatting": '4 text captions overlaying the "Gru\'s Plan" meme.',
    },
    {
        "id": "438680",
        "title": "Batman Slapping Robin",
        "box_count": 2,
        "explanation": "The humor in the Batman Slapping Robin meme comes from the absurdity of Batman slapping Robin in various situations. The dynamic between the two characters creates a comedic contrast, with Batman being serious and authoritative while Robin is often portrayed as naive or making silly mistakes. The exaggerated nature of the slap adds to the humor, making it a classic meme format that can be used to depict a wide range of humorous scenarios.",
        "formatting": '2 text captions overlaying the "Batman Slapping Robin" meme.',
    },
    {
        "id": "135256802",
        "title": "Epic Handshake",
        "box_count": 3,
        "explanation": "The Epic Handshake meme is funny because it typically consists of two unlikely characters or groups coming together in a dramatic and exaggerated way, often accompanied by epic music or lighting effects. The humor comes from the unexpected pairing of the characters and the over-the-top presentation, creating a sense of absurdity and exaggeration.",
        "formatting": '3 text captions overlaying the "Epic Handshake" meme.',
    },
    {
        "id": "80707627",
        "title": "Sad Pablo Escobar",
        "box_count": 3,
        "explanation": "The Sad Pablo Escobar meme typically features a photo of Pablo Escobar looking sad or disappointed with a humorous caption added to convey a sense of irony. The humor often comes from juxtaposing Escobar's serious or intimidating image with a lighthearted or relatable situation. It's a form of dark humor that plays on the notorious criminal's larger-than-life persona.",
        "formatting": '3 text captions overlaying the "Sad Pablo Escobar" meme.',
    },
    {
        "id": "97984",
        "title": "Disaster Girl",
        "box_count": 2,
        "explanation": "The humor of the Disaster Girl meme comes from the contrast between the innocent-looking girl in the photo and the destructive situation in the background. It creates a dark and unexpected element of humor.",
        "formatting": '2 text captions overlaying the "Disaster Girl" meme.',
    },
    {
        "id": "247375501",
        "title": "Buff Doge vs. Cheems",
        "box_count": 4,
        "explanation": 'The Buff Doge vs. Cheems meme is funny because of the exaggerated contrast between the muscular, confident "Buff Doge" and the small, insecure "Cheems" dog. The meme often uses broken English captions to show Cheems feeling inadequate compared to Buff Doge, creating a humorous dynamic between the two characters.',
        "formatting": '4 text captions overlaying the "Buff Doge vs. Cheems" meme.',
    },
    {
        "id": "252600902",
        "title": "Always Has Been",
        "box_count": 2,
        "explanation": "The Always Has Been meme relies on the element of surprise and absurdity. The punchline usually reveals something unexpected or ridiculous, such as one astronaut realizing they are about to shoot their friend in space. This sudden twist creates humor and generates laughs from the audience.",
        "formatting": '2 text captions overlaying the "Always Has Been" meme.',
    },
    {
        "id": "188390779",
        "title": "Woman Yelling At Cat",
        "box_count": 2,
        "explanation": "The humor in the Woman Yelling At Cat meme comes from the contrast between the intense emotion displayed by the woman and the seemingly unbothered and uninterested expression of the cat. This incongruity creates a humorous situation that people find entertaining. Additionally, the captions added to the meme often play on common scenarios or conflicts that many people can relate to, adding to its humor.",
        "formatting": '2 text captions overlaying the "Woman Yelling At Cat" meme.',
    },
    {
        "id": "322841258",
        "title": "Anakin Padme 4 Panel",
        "box_count": 3,
        "explanation": "The Anakin Padme 4 Panel meme is funny because it uses humor to depict Anakin Skywalker from Star Wars as being overly possessive or jealous of Padme Amidala, his love interest. This meme format often showcases Anakin's irrational behavior in a humorous way, highlighting the character's flaws and making light of his insecurities.",
        "formatting": '3 text captions overlaying the "Anakin Padme 4 Panel" meme.',
    },
    {
        "id": "161865971",
        "title": "Marked Safe From",
        "box_count": 2,
        "explanation": 'The humor in the "Marked Safe From" meme lies in the creative and absurd events or situations that people humorously announce themselves as being safe from. It often involves situations where being "safe" is not typically necessary or expected, such as being safe from fictional characters or everyday occurrences. The contrast between the seriousness of the original Facebook safety check feature and the lighthearted, nonsensical scenarios in the meme adds to its humor.',
        "formatting": '2 text captions overlaying the "Marked Safe From" meme.',
    },
    {
        "id": "91538330",
        "title": "X, X Everywhere",
        "box_count": 2,
        "explanation": 'The "X, X Everywhere" meme typically highlights a particular trend, joke, or situation by depicting it as being everywhere. This exaggeration can be humorous because it overemphasizes the prevalence of the subject in a comical way. The repetition of "X, X Everywhere" format adds to the humor by creating a sense of absurdity and amplifying the perceived ubiquity of the theme being referenced.',
        "formatting": '2 text captions overlaying the "X, X Everywhere" meme.',
    },
    {
        "id": "110163934",
        "title": "I Bet He's Thinking About Other Women",
        "box_count": 2,
        "explanation": 'The humor in the "I Bet He\'s Thinking About Other Women" meme typically stems from the unexpected or quirky thoughts that the person might be having instead of what you would typically assume. The contrast between the serious or mundane situation and the absurd or humorous thoughts can make it funny.',
        "formatting": '2 text captions overlaying the "I Bet He\'s Thinking About Other Women" meme.',
    },
    {
        "id": "178591752",
        "title": "Tuxedo Winnie The Pooh",
        "box_count": 2,
        "explanation": "The Tuxedo Winnie The Pooh meme is funny because it takes the lovable and innocent character of Winnie the Pooh and puts him in a sophisticated and classy tuxedo outfit, creating a humorous contrast. The meme is often used to convey a sense of elegance or formality in a comical way.",
        "formatting": '2 text captions overlaying the "Tuxedo Winnie The Pooh" meme.',
    },
    {
        "id": "309868304",
        "title": "Trade Offer",
        "box_count": 3,
        "explanation": "The Trade Offer meme humorously depicts a situation where someone offers a trade that is completely unbalanced or absurd. The humor comes from the exaggerated and often nonsensical nature of the trade offers, which highlight the ridiculousness of some trade proposals in real life.",
        "formatting": '3 text captions overlaying the "Trade Offer" meme.',
    },
    {
        "id": "102156234",
        "title": "Mocking Spongebob",
        "box_count": 2,
        "explanation": "The Mocking SpongeBob meme is funny because it features an image of SpongeBob SquarePants imitating a stereotypical behavior of mocking or making fun of someone else. The image is usually paired with mocking or mimicking text, adding humor to situations where someone is being ridiculed or teased.",
        "formatting": '2 text captions overlaying the "Mocking Spongebob" meme.',
    },
    {
        "id": "93895088",
        "title": "Expanding Brain",
        "box_count": 4,
        "explanation": 'The Expanding Brain meme is funny because it humorously represents the idea of increasing levels of intelligence or knowledge on a particular subject. The progression from a small brain to an increasingly larger brain with more "expansion" represents the concept of someone becoming progressively smarter or having deeper insights on a topic. The humor often comes from the exaggerated and sometimes absurd comparisons made in each level of the meme.',
        "formatting": '4 text captions overlaying the "Expanding Brain" meme.',
    },
    {
        "id": "79132341",
        "title": "Bike Fall",
        "box_count": 3,
        "explanation": "The humor in the Bike Fall meme often comes from the unexpected or slapstick nature of someone falling off a bike in a humorous or exaggerated way. It can also be funny because it's a relatable situation that many people have experienced themselves.",
        "formatting": '3 text captions overlaying the "Bike Fall" meme.',
    },
    {
        "id": "180190441",
        "title": "They're The Same Picture",
        "box_count": 3,
        "explanation": 'The humor in the "They\'re The Same Picture" meme lies in the absurdity of comparing two seemingly identical images and pointing out minor differences as if they are groundbreaking revelations. It often highlights how people tend to overanalyze and make unnecessary distinctions between things that are essentially the same. The meme plays on the idea that sometimes differences are exaggerated for comedic effect.',
        "formatting": '3 text captions overlaying the "They\'re The Same Picture" meme.',
    },
    {
        "id": "148909805",
        "title": "Monkey Puppet",
        "box_count": 2,
        "explanation": 'The Monkey Puppet meme, also known as "Awkward Look Monkey Puppet," features an image of a puppet monkey with a wide-eyed, tense expression. It is often used to convey a sense of awkwardness, discomfort, or hesitation in various situations. The humor in this meme comes from the expressive and relatable nature of the monkey puppet\'s face, making it perfect for illustrating moments of indecision or social awkwardness in a humorous way.',
        "formatting": '2 text captions overlaying the "Monkey Puppet" meme.',
    },
    {
        "id": "61579",
        "title": "One Does Not Simply",
        "box_count": 2,
        "explanation": 'The humor in the "One Does Not Simply" meme comes from the contrast between the serious tone of the text overlaid on the image of Boromir from "Lord of the Rings" and the often mundane or trivial statement being made. The meme\'s template has been used to convey a sense of exaggeration or seriousness in a comically over-the-top manner.',
        "formatting": '2 text captions overlaying the "One Does Not Simply" meme.',
    },
    {
        "id": "1035805",
        "title": "Boardroom Meeting Suggestion",
        "box_count": 4,
        "explanation": "The humor in the Boardroom Meeting Suggestion meme comes from the absurd or ridiculous suggestions that are portrayed in the image. The meme typically involves a boardroom meeting scenario where one person suggests something outlandish or unconventional, leading to humorous reactions from the other individuals in the room. The juxtaposition of the serious business setting with the silly suggestions is what makes this meme funny to many people.",
        "formatting": '4 text captions overlaying the "Boardroom Meeting Suggestion" meme.',
    },
    {
        "id": "61544",
        "title": "Success Kid",
        "box_count": 2,
        "explanation": "The humor in the Success Kid meme comes from the juxtaposition of the baby's determined and triumphant expression with the often mundane or relatable situations or achievements that are described in the caption. The idea that even a baby can have such a triumphant moment adds a humorous touch to the meme.",
        "formatting": '2 text captions overlaying the "Success Kid" meme.',
    },
    {
        "id": "101470",
        "title": "Ancient Aliens",
        "box_count": 2,
        "explanation": "The Ancient Aliens meme is funny because it takes a serious and speculative documentary series about extraterrestrial theories and turns it into a meme format that can be used to apply outlandish and humorous explanations to everyday situations or phenomena. The meme often features a close-up of Giorgio A. Tsoukalos, a regular contributor to the series, accompanied by exaggerated text that humorously attributes mysterious events or historical occurrences to aliens. The ironic and absurd nature of the meme, coupled with Tsoukalos' distinctive appearance and the dramatic tone of the original show, make it a popular source of humor and parody on the internet.",
        "formatting": '2 text captions overlaying the "Ancient Aliens" meme.',
    },
    {
        "id": "3218037",
        "title": "This Is Where I'd Put My Trophy If I Had One",
        "box_count": 2,
        "explanation": "The humor in this meme comes from the absurdity of the situation, as the character is expressing a desire for a trophy even though they clearly don't have one. It's a humorous way of acknowledging a lack of achievement or recognition in a self-deprecating manner.",
        "formatting": '2 text captions overlaying the "This Is Where I\'d Put My Trophy If I Had One" meme.',
    },
    {
        "id": "27813981",
        "title": "Hide the Pain Harold",
        "box_count": 2,
        "explanation": "The humor in the Hide the Pain Harold meme comes from the contrast between the external appearance of smiling and looking happy, and the internal feelings of pain or discomfort that Harold is supposedly hiding. People find humor in the relatability of putting on a facade and trying to maintain a composed, happy image even when things might not be going well internally. Harold's expression and the overall concept have become a popular meme template for various situations where someone is trying to hide their true emotions.",
        "formatting": '2 text captions overlaying the "Hide the Pain Harold" meme.',
    },
    {
        "id": "195515965",
        "title": "Clown Applying Makeup",
        "box_count": 4,
        "explanation": "The Clown Applying Makeup meme is funny because it plays on the idea of someone trying to hide their true emotions or intentions behind a facade. The image of a clown meticulously applying makeup can be used to highlight situations where someone is being insincere or deceitful. It's a humorous way of pointing out hypocrisy or fake behavior in a light-hearted manner.",
        "formatting": '4 text captions overlaying the "Clown Applying Makeup" meme.',
    },
    {
        "id": "124055727",
        "title": "Y'all Got Any More Of That",
        "box_count": 2,
        "explanation": "The \"Y'all Got Any More Of That\" meme is funny because it typically involves a character looking desperate or eager for something they want more of. The humor comes from the exaggerated or relatable situations in which someone just can't get enough of something. This meme is often used in a light-hearted way to highlight moments when people are eagerly seeking or consuming something.",
        "formatting": '2 text captions overlaying the "Y\'all Got Any More Of That" meme.',
    },
    {
        "id": "370867422",
        "title": "Megamind peeking",
        "box_count": 2,
        "explanation": "The Megamind peeking meme is funny because it shows the character peeking from behind a corner or a wall, often representing curiosity or mischief. This can be applied to various situations where someone is eavesdropping or spying on something. The exaggerated expression on Megamind's face adds to the humor of the meme.",
        "formatting": '2 text captions overlaying the "Megamind peeking" meme.',
    },
    {
        "id": "55311130",
        "title": "This Is Fine",
        "box_count": 2,
        "explanation": 'The humor in the "This is Fine" meme comes from the juxtaposition of the dog calmly sitting in a room engulfed in flames, while uttering the phrase "This is fine." It is a satirical and exaggerated representation of people trying to maintain composure in the face of chaos or stressful situations. The disconnect between the dog\'s calm demeanor and the dire circumstances surrounding it is what makes the meme funny and relatable in a darkly humorous way.',
        "formatting": '2 text captions overlaying the "This Is Fine" meme.',
    },
    {
        "id": "224015000",
        "title": "Bernie Sanders Once Again Asking",
        "box_count": 2,
        "explanation": 'The humor in the Bernie Sanders "Once Again Asking" meme comes from Sanders appearing persistent and relatable in his quest to garner support or attention for something. The repetition of the phrase "once again asking" can be applied humorously to various scenarios, making it versatile and entertaining. Additionally, the image of Sanders in his practical winter attire and earnest expression adds to the charm of the meme.',
        "formatting": '2 text captions overlaying the "Bernie Sanders Once Again Asking" meme.',
    },
    {
        "id": "316466202",
        "title": "where monkey",
        "box_count": 2,
        "explanation": 'The "Monkey Looking Away" meme is humorous because it presents a scenario where someone or something is intentionally ignoring an obvious option or solution. The image of the monkey looking away conveys a sense of deliberate stubbornness or nonchalance in the face of a clear choice. This can be applied to a wide range of situations, making it a versatile and relatable meme template.',
        "formatting": '2 text captions overlaying the "where monkey" meme.',
    },
    {
        "id": "119139145",
        "title": "Blank Nut Button",
        "box_count": 2,
        "explanation": 'The Blank Nut Button meme is a play on the popular "Nut Button" meme, featuring a red button with the word "nut" on it. In the Blank Nut Button meme, the button is left empty, creating a humorous blank space that can be filled in with various phrases or images to create comedic effect. People often use this format to come up with clever and unexpected punchlines or statements, making it a versatile and amusing meme template.',
        "formatting": '2 text captions overlaying the "Blank Nut Button" meme.',
    },
    {
        "id": "28251713",
        "title": "Oprah You Get A",
        "box_count": 2,
        "explanation": "The humor in the Oprah You Get A meme comes from the exaggerated generosity depicted in the meme. Oprah's excited and generous expression is often used to humorously suggest that everyone is getting something amazing, no matter how unrealistic or over-the-top it may be.",
        "formatting": '2 text captions overlaying the "Oprah You Get A" meme.',
    },
    {
        "id": "100777631",
        "title": "Is This A Pigeon",
        "box_count": 3,
        "explanation": 'The humor in the "Is This A Pigeon?" meme comes from the misinterpretation of the situation depicted in the scene. The meme features a character misidentifying a butterfly as a pigeon, which is relatable and humorous because it highlights moments where someone gets things hilariously wrong or misunderstands a situation. It can be used in various contexts to poke fun at instances where someone is confused or mistaken about something obvious.',
        "formatting": '3 text captions overlaying the "Is This A Pigeon" meme.',
    },
    {
        "id": "226297822",
        "title": "Panik Kalm Panik",
        "box_count": 3,
        "explanation": 'The "Panik Kalm Panik" meme format involves three increasingly intense stages of panic, with the subject gradually escalating from a state of calm to full-blown panic. The humor lies in the exaggerated reaction and the relatability of feeling overwhelmed by a situation, leading to a humorous and relatable representation of stress or anxiety.',
        "formatting": '3 text captions overlaying the "Panik Kalm Panik" meme.',
    },
    {
        "id": "252758727",
        "title": "Mother Ignoring Kid Drowning In A Pool",
        "box_count": 4,
        "explanation": "I'm sorry, but that topic is not appropriate or funny to make a meme about. It is important to remember that memes should always be lighthearted and respectful. If you have any other questions about internet memes, feel free to ask.",
        "formatting": '4 text captions overlaying the "Mother Ignoring Kid Drowning In A Pool" meme.',
    },
    {
        "id": "259237855",
        "title": "Laughing Leo",
        "box_count": 2,
        "explanation": 'The Laughing Leo meme features a still image of actor Leonardo DiCaprio in the movie "Django Unchained" where his character Calvin Candie is laughing uproariously. The meme is often used to express joy or amusement in response to a humorous situation or joke. The humor lies in the exaggerated and enthusiastic expression of laughter on DiCaprio\'s face, making it a popular reaction image across social media platforms.',
        "formatting": '2 text captions overlaying the "Laughing Leo" meme.',
    },
    {
        "id": "166969924",
        "title": "Flex Tape",
        "box_count": 3,
        "explanation": "The Flex Tape meme is a humorous way of portraying exaggerated and over-the-top solutions to everyday problems. It often features images or videos of Flex Tape being used in absurd ways to fix or repair things that seem impossible or impractical. The humor comes from the ridiculousness of the suggested solutions and the unexpected creativity in using a product like Flex Tape in unconventional ways.",
        "formatting": '3 text captions overlaying the "Flex Tape" meme.',
    },
    {
        "id": "99683372",
        "title": "Sleeping Shaq",
        "box_count": 2,
        "explanation": "The Sleeping Shaq meme typically features an image of retired NBA player Shaquille O'Neal looking very relaxed and peaceful while sleeping. The humor comes from the contrast between his large, imposing stature and the innocent expression while he is asleep. The meme is often used to make light-hearted jokes or reference situations where someone appears unexpectedly comfortable or relaxed.",
        "formatting": '2 text captions overlaying the "Sleeping Shaq" meme.',
    },
    {
        "id": "89370399",
        "title": "Roll Safe Think About It",
        "box_count": 2,
        "explanation": "The Roll Safe Think About It meme features a screenshot of actor Kayode Ewumi pointing to his temple with a serious expression, accompanied by text offering sarcastic or humorous advice. The humor comes from the combination of the serious expression and the often absurd or illogical advice being given in the text. It's like a tongue-in-cheek way of pretending to give wise counsel or insight.",
        "formatting": '2 text captions overlaying the "Roll Safe Think About It" meme.',
    },
    {
        "id": "247113703",
        "title": "A train hitting a school bus",
        "box_count": 2,
        "explanation": "I'm sorry, but I am not aware of a specific meme involving an A train hitting a school bus. It's important to remember that memes can vary widely in humor and meaning, and some may not be appropriate or may not resonate with everyone. If you have any other meme-related questions, feel free to ask!",
        "formatting": '2 text captions overlaying the "A train hitting a school bus" meme.',
    },
    {
        "id": "509760957",
        "title": "Travis Kelce screaming",
        "box_count": 2,
        "explanation": "The meme features a still of Travis Kelce, a football player, looking like he's screaming in passion or anger. It's funny because the exaggerated expression on his face can be applied to various situations, creating humorous and relatable scenarios. People enjoy using this meme to convey intense emotions in a playful way.",
        "formatting": '2 text captions overlaying the "Travis Kelce screaming" meme.',
    },
    {
        "id": "177682295",
        "title": "You Guys are Getting Paid",
        "box_count": 2,
        "explanation": 'The humor in the "You Guys are Getting Paid?" meme comes from the incredulous and sarcastic tone of the statement. The meme is often used to highlight situations where people are receiving compensation for seemingly trivial or straightforward tasks, often in a humorous or ironic manner. It plays on the disbelief that someone could be paid for such an easy or ridiculous job, making it a relatable and amusing concept for many people.',
        "formatting": '2 text captions overlaying the "You Guys are Getting Paid" meme.',
    },
    {
        "id": "84341851",
        "title": "Evil Kermit",
        "box_count": 2,
        "explanation": "The Evil Kermit meme is funny because it shows a contrast between our good intentions (represented by regular Kermit) and our darker, selfish desires (represented by Evil Kermit). It's relatable because it highlights the internal struggles we all face when making decisions or choices. It's humorous to see a well-known character like Kermit the Frog being used in this way to reflect our internal conflicts.",
        "formatting": '2 text captions overlaying the "Evil Kermit" meme.',
    },
    {
        "id": "284929871",
        "title": "They don't know",
        "box_count": 2,
        "explanation": 'The humor in the "They don\'t know" meme typically comes from the absurd or unexpected scenarios people come up with where a group of people is depicted as being unaware of something unusual happening right in front of them. The contrast between the oblivious group and the strange or amusing situation can create humor for viewers.',
        "formatting": '2 text captions overlaying the "They don\'t know" meme.',
    },
    {
        "id": "21735",
        "title": "The Rock Driving",
        "box_count": 2,
        "explanation": 'The humor in The Rock Driving meme comes from pairing an image of Dwayne "The Rock" Johnson looking intense and focused, with humorous captions suggesting he is driving to various unusual or ridiculous destinations or situations. The contrast between his serious expression and the absurdity of the scenarios creates comedic effect.',
        "formatting": '2 text captions overlaying the "The Rock Driving" meme.',
    },
    {
        "id": "114585149",
        "title": "Inhaling Seagull",
        "box_count": 4,
        "explanation": "The humor in the Inhaling Seagull meme comes from the unexpected and exaggerated pose of the seagull in the image. The seagull appears to be inhaling deeply and dramatically, which is not what one would typically expect from a bird. This absurd and exaggerated depiction of the seagull adds to the comedic value of the meme.",
        "formatting": '4 text captions overlaying the "Inhaling Seagull" meme.',
    },
    {
        "id": "155067746",
        "title": "Surprised Pikachu",
        "box_count": 3,
        "explanation": "The Surprised Pikachu meme is funny because it features the iconic Pokémon character Pikachu with a shocked expression, despite the situation being one that should have been predicted or expected. The humor comes from the exaggerated reaction of Pikachu in response to something seemingly obvious or unsurprising. It has become a versatile meme format used to convey surprise or disbelief in various scenarios.",
        "formatting": '3 text captions overlaying the "Surprised Pikachu" meme.',
    },
    {
        "id": "427308417",
        "title": "0 days without (Lenny, Simpsons)",
        "box_count": 2,
        "explanation": 'The "0 days without (blank)" meme, featuring the character Lenny from The Simpsons, is humorous because it humorously highlights the repetitive and often predictable nature of certain situations. By constantly resetting the counter back to zero days without a particular occurrence, the meme illustrates how frequently that particular event happens - creating a humorous and relatable commentary on everyday life.',
        "formatting": '2 text captions overlaying the "0 days without (Lenny, Simpsons)" meme.',
    },
    {
        "id": "134797956",
        "title": "American Chopper Argument",
        "box_count": 5,
        "explanation": 'The humor in the American Chopper Argument meme comes from the dramatic and intense expressions of the characters from the TV show "American Chopper" overlaid with humorous text to represent a debate or argument between two conflicting ideas or preferences. The meme is funny because of the exaggerated reactions and the versatility of the format to depict a wide range of funny and relatable scenarios.',
        "formatting": '5 text captions overlaying the "American Chopper Argument" meme.',
    },
    {
        "id": "135678846",
        "title": "Who Killed Hannibal",
        "box_count": 3,
        "explanation": 'The humor in the "Who Killed Hannibal" meme comes from a combination of shock, unexpectedness, and absurdity. The meme portrays a nonchalant response to a serious or dramatic situation, which creates a humorous contrast and catches people off guard. It\'s essentially a playful way of making light of intense or suspenseful moments by introducing a completely unrelated joke or question.',
        "formatting": '3 text captions overlaying the "Who Killed Hannibal" meme.',
    },
    {
        "id": "101956210",
        "title": "Whisper and Goosebumps",
        "box_count": 2,
        "explanation": 'The Whisper and Goosebumps meme is funny because it pairs random, everyday situations with the cover of a Goosebumps book titled "Say Cheese and Die". The juxtaposition of the mundane activities with the spooky book cover creates humor through unexpected contrast.',
        "formatting": '2 text captions overlaying the "Whisper and Goosebumps" meme.',
    },
    {
        "id": "267889046",
        "title": "bell curve",
        "box_count": 4,
        "explanation": "The bell curve meme is funny because it humorously depicts the distribution of a particular trait or behavior in a population using a bell curve graph. It often exaggerates stereotypes or common perceptions about different groups of people in a humorous way.",
        "formatting": '4 text captions overlaying the "bell curve" meme.',
    },
    {
        "id": "119215120",
        "title": "Types of Headaches meme",
        "box_count": 2,
        "explanation": 'The "Types of Headaches" meme is funny because it humorously categorizes different scenarios or situations as different types of headaches. People can relate to the situations depicted in the meme and find humor in the exaggerated descriptions of these "headaches". It\'s a way of playfully categorizing common annoyances or frustrations that people experience in their daily lives.',
        "formatting": '2 text captions overlaying the "Types of Headaches meme" meme.',
    },
    {
        "id": "216523697",
        "title": "All My Homies Hate",
        "box_count": 2,
        "explanation": 'The humor in the "All My Homies Hate" meme comes from the exaggerated and absurd scenarios in which the group of friends collectively dislikes something or someone. It often features a comically diverse group of characters united in their strong, irrational, and humorous aversion. The absurdity of the situations depicted in the meme is what makes it funny to many people.',
        "formatting": '2 text captions overlaying the "All My Homies Hate" meme.',
    },
    {
        "id": "123999232",
        "title": "The Scroll Of Truth",
        "box_count": 2,
        "explanation": "The humor in The Scroll of Truth meme comes from the abrupt and unexpected revelation presented on the scroll. The meme typically involves a character excitedly opening a scroll only to discover a harsh truth or unexpected twist written on it. The contrast between the anticipation of the character and the humorously blunt nature of the truth is what makes this meme funny.",
        "formatting": '2 text captions overlaying the "The Scroll Of Truth" meme.',
    },
    {
        "id": "6235864",
        "title": "Finding Neverland",
        "box_count": 3,
        "explanation": "The Finding Neverland meme is funny because it typically features a character looking at something with a mix of disbelief and amazement, as if they have finally found something they have been searching for. This expression is often paired with humorous or exaggerated captions, making it a popular template for creating funny scenarios or observations.",
        "formatting": '3 text captions overlaying the "Finding Neverland" meme.',
    },
    {
        "id": "224514655",
        "title": "Anime Girl Hiding from Terminator",
        "box_count": 2,
        "explanation": "The humor in this meme comes from the contrast between the cute and innocent anime girl character trying to hide from the menacing and powerful Terminator. The juxtaposition of the two characters from seemingly different worlds creates a humorous and absurd situation.",
        "formatting": '2 text captions overlaying the "Anime Girl Hiding from Terminator" meme.',
    },
    {
        "id": "61556",
        "title": "Grandma Finds The Internet",
        "box_count": 2,
        "explanation": 'The humor in the "Grandma Finds The Internet" meme often comes from the portrayal of older generations struggling to grasp the complexities of modern technology and online culture. It plays on the stereotypical image of a grandparent being unfamiliar with the internet and its various quirks, leading to humorous misunderstandings or awkward interactions. The meme captures the generational gap and highlights the comedic moments that arise from this disconnect.',
        "formatting": '2 text captions overlaying the "Grandma Finds The Internet" meme.',
    },
    {
        "id": "221578498",
        "title": "Grant Gustin over grave",
        "box_count": 2,
        "explanation": "The Grant Gustin over grave meme plays on the idea of a dramatic or intense moment being interrupted by something random or silly. The contrast between the serious tone of the original scene and the humorous addition of Grant Gustin's photo creates a funny and unexpected juxtaposition. This contrast is what makes the meme humorous to many people.",
        "formatting": '2 text captions overlaying the "Grant Gustin over grave" meme.',
    },
    {
        "id": "50421420",
        "title": "Disappointed Black Guy",
        "box_count": 2,
        "explanation": "The Disappointed Black Guy meme typically features a man looking disappointed or unimpressed, which can be used to convey a sense of disappointment or disapproval in a humorous way. The humor often comes from the relatable situations where one might feel similarly disappointed or unimpressed.",
        "formatting": '2 text captions overlaying the "Disappointed Black Guy" meme.',
    },
    {
        "id": "101288",
        "title": "Third World Skeptical Kid",
        "box_count": 2,
        "explanation": "The humor in the Third World Skeptical Kid meme often comes from the context in which the child's expression is used. The juxtaposition of the child's skeptical expression with various statements or situations can create a humorous contrast, often highlighting absurdity or irony. The meme can also be used to challenge assumptions or stereotypes in a lighthearted way.",
        "formatting": '2 text captions overlaying the "Third World Skeptical Kid" meme.',
    },
    {
        "id": "77045868",
        "title": "Pawn Stars Best I Can Do",
        "box_count": 2,
        "explanation": 'The humor in the Pawn Stars "Best I Can Do" meme comes from the sarcastic and dismissive response given by the character in the show, Rick Harrison, when evaluating an item. The meme is often used to humorously reference situations where someone is offering something of perceived value, only to be met with a lowball offer or rejection. The contrast between the seriousness of the situation and the nonchalant response in the meme adds to its comedic effect.',
        "formatting": '2 text captions overlaying the "Pawn Stars Best I Can Do" meme.',
    },
    {
        "id": "171305372",
        "title": "Soldier protecting sleeping child",
        "box_count": 3,
        "explanation": "The humor in this meme comes from the unexpected or absurd scenarios that can be depicted. The contrast between the serious and protective soldier and the innocent sleeping child can be used to create humorous or ironic situations in various contexts.",
        "formatting": '3 text captions overlaying the "Soldier protecting sleeping child" meme.',
    },
    {
        "id": "234202281",
        "title": "AJ Styles & Undertaker",
        "box_count": 2,
        "explanation": "The AJ Styles & Undertaker meme humorously captures the dynamic between veteran and newcomer in various scenarios. It plays on the idea of an experienced individual mentoring someone who is new to a certain situation, often resulting in comical or unexpected outcomes. The meme format allows for creative and amusing comparisons between the two characters in different contexts.",
        "formatting": '2 text captions overlaying the "AJ Styles & Undertaker" meme.',
    },
    {
        "id": "67452763",
        "title": "Squidward window",
        "box_count": 2,
        "explanation": "The humor in the Squidward window meme comes from the relatable feeling of wanting to be included or involved in something, only to be left out or ignored, much like how Squidward always seemed to be on the outside looking in on SpongeBob and Patrick's adventures. The image of Squidward sadly looking out of a window adds to the humor and captures the feeling of being left out in a comical way.",
        "formatting": '2 text captions overlaying the "Squidward window" meme.',
    },
    {
        "id": "5496396",
        "title": "Leonardo Dicaprio Cheers",
        "box_count": 2,
        "explanation": "The humor in the Leonardo DiCaprio Cheers meme comes from the relatable and lighthearted nature of the image. It shows DiCaprio raising a glass in a cheers gesture, which is often used humorously to celebrate small victories or mundane achievements in a playful way. Additionally, the expression on his face in the image adds to the comedic effect, making it a popular and funny meme template.",
        "formatting": '2 text captions overlaying the "Leonardo Dicaprio Cheers" meme.',
    },
    {
        "id": "110133729",
        "title": "spiderman pointing at spiderman",
        "box_count": 2,
        "explanation": "The humor in the Spiderman pointing at Spiderman meme comes from the absurdity and meta nature of the situation. It plays with the idea of self-reference and recursion, as well as drawing attention to the similarities and differences between the two Spiderman characters. This creates a humorous and self-aware visual gag that fans of the Spiderman franchise can enjoy.",
        "formatting": '2 text captions overlaying the "spiderman pointing at spiderman" meme.',
    },
    {
        "id": "61520",
        "title": "Futurama Fry",
        "box_count": 2,
        "explanation": 'The humor in the Futurama Fry meme comes from the expression on Fry\'s face and the caption that usually represents a sudden realization, doubt, or confusion about something. It often captures moments when we all have those relatable "not sure if..." thoughts or skeptical reactions to a situation.',
        "formatting": '2 text captions overlaying the "Futurama Fry" meme.',
    },
    {
        "id": "91998305",
        "title": "Drake Blank",
        "box_count": 2,
        "explanation": "The Drake Blank meme is funny because it uses two contrasting images of Drake (Canadian rapper and actor) to represent different choices or preferences. The humor often comes from the relatable and sometimes absurd contrasts between the two options, and the format allows for a wide range of creative and humorous interpretations.",
        "formatting": '2 text captions overlaying the "Drake Blank" meme.',
    },
    {
        "id": "371619279",
        "title": "Megamind no bitches",
        "box_count": 2,
        "explanation": 'The Megamind "no bitches" meme is funny because it features a character from the animated movie "Megamind" saying "no bitches" in a humorous and unexpected way. The juxtaposition of the character\'s expression and the phrase "no bitches" can create a comedic and absurd connotation, making it a popular meme format for various jokes and scenarios.',
        "formatting": '2 text captions overlaying the "Megamind no bitches" meme.',
    },
    {
        "id": "14371066",
        "title": "Star Wars Yoda",
        "box_count": 2,
        "explanation": "The Yoda memes typically involve the character Yoda from the Star Wars franchise speaking in a humorous or nonsensical way, often referencing popular internet or meme culture. The humor often comes from the unexpected or amusing juxtaposition of Yoda's wise and serious demeanor with the silly or irreverent content of the meme.",
        "formatting": '2 text captions overlaying the "Star Wars Yoda" meme.',
    },
    {
        "id": "360597639",
        "title": "whe i'm in a competition and my opponent is",
        "box_count": 2,
        "explanation": 'The humor in the "When I\'m in a competition and my opponent is..." meme lies in the unexpected or extreme scenarios that are depicted in the images. The meme typically shows a very intense or exaggerated situation as the "opponent" in a competition, which contrasts with the more mundane or normal situation the person is in. This exaggeration creates a humorous comparison that people can relate to in their own experiences of competition or rivalry.',
        "formatting": '2 text captions overlaying the "whe i\'m in a competition and my opponent is" meme.',
    },
    {
        "id": "175540452",
        "title": "Unsettled Tom",
        "box_count": 2,
        "explanation": "The Unsettled Tom meme features a picture of a distressed-looking cat, which is often used to represent feelings of discomfort, unease, or confusion. Many find humor in using this image to convey relatable situations or reactions to various scenarios, making it a popular and versatile meme format.",
        "formatting": '2 text captions overlaying the "Unsettled Tom" meme.',
    },
    {
        "id": "342785297",
        "title": "Gus Fring we are not the same",
        "box_count": 3,
        "explanation": 'The humor in the "Gus Fring we are not the same" meme lies in the comparison between two seemingly similar things or situations, with one being clearly superior or more powerful than the other. This meme format plays off the character of Gus Fring from the TV show "Breaking Bad," known for his calm and collected demeanor despite being a ruthless drug lord. The meme often contrasts something mundane or inferior with a superior or extraordinary counterpart to create a humorous and exaggerated comparison.',
        "formatting": '3 text captions overlaying the "Gus Fring we are not the same" meme.',
    },
    {
        "id": "91545132",
        "title": "Trump Bill Signing",
        "box_count": 2,
        "explanation": "The humor in the Trump Bill Signing meme usually comes from the juxtaposition of the serious and official context of a bill signing with President Trump's facial expressions, body language, or the presence of unexpected or humorous elements in the image. The meme often plays on Trump's image and personality, creating humorous scenarios that reflect current events or satirical commentary.",
        "formatting": '2 text captions overlaying the "Trump Bill Signing" meme.',
    },
    {
        "id": "29617627",
        "title": "Look At Me",
        "box_count": 2,
        "explanation": 'The "Look At Me" meme typically features a person or character demanding attention or acknowledgment in a humorous or exaggerated way. It often plays on the idea of seeking validation or recognition, which can be relatable and funny to many people. The humor comes from the exaggerated expressions or actions of the person in the meme and how it can be applied to various situations.',
        "formatting": '2 text captions overlaying the "Look At Me" meme.',
    },
    {
        "id": "61532",
        "title": "The Most Interesting Man In The World",
        "box_count": 2,
        "explanation": 'The humor in "The Most Interesting Man in the World" meme comes from the exaggerated and often absurd statements that follow the template "I don\'t always [do something], but when I do, [something humorous or unlikely happens]". This meme plays on the idea of someone being so interesting and impressive that they can accomplish extraordinary feats or have peculiar habits. The juxtaposition of the serious and sophisticated looking image with the humorous caption adds to the comedic effect.',
        "formatting": '2 text captions overlaying the "The Most Interesting Man In The World" meme.',
    },
    {
        "id": "196652226",
        "title": "Spongebob Ight Imma Head Out",
        "box_count": 2,
        "explanation": 'The humor in the Spongebob "Ight Imma head out" meme comes from the relatability of the situation. The image of Spongebob confidently walking away is often used in situations where someone decides to leave or exit a conversation or situation. The absurdity of Spongebob\'s expression and the simplicity of the phrase make it humorous in various contexts.',
        "formatting": '2 text captions overlaying the "Spongebob Ight Imma Head Out" meme.',
    },
    {
        "id": "137501417",
        "title": "Friendship ended",
        "box_count": 2,
        "explanation": 'The Friendship ended meme is funny because of its dramatic and over-the-top nature. It typically features two characters with one of them saying "Friendship ended with [person], now [new person] is my best friend." The sudden and extreme shift in loyalty can be seen as humorous and exaggerated.',
        "formatting": '2 text captions overlaying the "Friendship ended" meme.',
    },
    {
        "id": "187102311",
        "title": "Three-headed Dragon",
        "box_count": 4,
        "explanation": "The Three-headed Dragon meme typically features three heads representing different aspects or choices, with each head expressing a different opinion or reaction. The humor often comes from the juxtaposition of the three heads and their varying perspectives on a situation, making it a humorous representation of internal conflicts or decision-making processes.",
        "formatting": '4 text captions overlaying the "Three-headed Dragon" meme.',
    },
    {
        "id": "142009471",
        "title": "is this butterfly",
        "box_count": 3,
        "explanation": 'The "Is This a Pigeon?" meme features a screenshot from the anime series "The Brave Fighter of Sun Fighbird," in which a character mistakenly identifies a butterfly as a pigeon. The humor in this meme comes from the absurdity of the misidentification and the relatability of making similar mistakes in everyday life. The meme has been used to comment on situations where someone misunderstands or misinterprets something obvious, resulting in comedic effect.',
        "formatting": '3 text captions overlaying the "is this butterfly" meme.',
    },
    {
        "id": "177984372",
        "title": "What Gives People Feelings of Power",
        "box_count": 2,
        "explanation": 'The humor in the "What Gives People Feelings of Power" meme lies in the absurdity and randomness of the images and captions paired together. The juxtaposition of seemingly unrelated images with the caption "What gives people feelings of power" creates a humorous and often nonsensical effect that resonates with internet users. Additionally, the concept itself of exploring what makes people feel empowered in a comical and exaggerated way adds to the humor of the meme.',
        "formatting": '2 text captions overlaying the "What Gives People Feelings of Power" meme.',
    },
    {
        "id": "162372564",
        "title": "Domino Effect",
        "box_count": 2,
        "explanation": "The Domino Effect meme typically involves a series of events or actions that lead to a humorous or unexpected outcome. The humor often comes from the escalating absurdity of each successive event, and the anticipation of how the chain reaction will ultimately play out. The meme's humor lies in the exaggeration and unrestrained creativity in connecting an initial action to a completely unrelated final outcome.",
        "formatting": '2 text captions overlaying the "Domino Effect" meme.',
    },
    {
        "id": "72525473",
        "title": "say the line bart! simpsons",
        "box_count": 3,
        "explanation": 'The humor in this meme lies in how it plays off the scene from "The Simpsons" where Bart is asked to repeat a line, but in the meme, a different character or object is shown saying the line instead, often leading to absurd or unexpected results. The humor comes from the unexpected or clever ways the meme is adapted to different situations.',
        "formatting": '3 text captions overlaying the "say the line bart! simpsons" meme.',
    },
    {
        "id": "92084495",
        "title": "Charlie Conspiracy (Always Sunny in Philidelphia)",
        "box_count": 2,
        "explanation": 'The "Charlie Conspiracy" meme from It\'s Always Sunny in Philadelphia is funny because it takes a scene from the show where the character Charlie puts together a conspiracy theory with various pictures and connections, and uses it to humorously illustrate wild, ridiculous, or nonsensical theories or explanations for everyday occurrences. This absurd and over-the-top interpretation of events is what makes the meme humorous to many people.',
        "formatting": '2 text captions overlaying the "Charlie Conspiracy (Always Sunny in Philidelphia)" meme.',
    },
    {
        "id": "145139900",
        "title": "Scooby doo mask reveal",
        "box_count": 4,
        "explanation": "The Scooby-Doo mask reveal meme is funny because it plays on the classic Scooby-Doo trope where the villain is always unmasked at the end of the episode. The meme takes this predictable reveal and puts a humorous twist on it by using it in various unexpected contexts, often revealing something surprising or ridiculous hidden underneath the mask. The element of surprise and the absurdity of the reveals make this meme humorous and entertaining.",
        "formatting": '4 text captions overlaying the "Scooby doo mask reveal" meme.',
    },
    {
        "id": "206151308",
        "title": "Spider Man Triple",
        "box_count": 3,
        "explanation": "The Spider Man Triple meme is funny because it shows three Spider-Man characters pointing at each other. It's a humorous and confusing loop of pointing fingers, creating a sense of irony and self-awareness. This meme is often used to humorously represent situations where multiple parties are all blaming each other for a mistake or problem.",
        "formatting": '3 text captions overlaying the "Spider Man Triple" meme.',
    },
    {
        "id": "478588645",
        "title": "Borat 2 Tonight Queen??",
        "box_count": 3,
        "explanation": 'The "Borat 2 Tonight Queen??" meme is funny because it plays on the iconic and sometimes awkward interactions between Borat and various characters in the movie. The question "Tonight Queen??" adds an element of randomness and absurdity to the meme, making it humorous and entertaining for fans of the Borat franchise.',
        "formatting": '3 text captions overlaying the "Borat 2 Tonight Queen??" meme.',
    },
    {
        "id": "20007896",
        "title": "c'mon do something",
        "box_count": 2,
        "explanation": 'The "C\'mon Do Something" meme features a photoshopped image of a character from the anime "Dragon Ball Z" with a humorous expression, accompanying the phrase "C\'mon, do something." The humor in this meme comes from the character\'s intense and challenging expression, paired with the playful and slightly taunting caption. It can be used in various contexts to express defiance or challenge someone to take action in a playful way.',
        "formatting": '2 text captions overlaying the "c\'mon do something" meme.',
    },
    {
        "id": "249257686",
        "title": "Bugs bunny communist",
        "box_count": 2,
        "explanation": "The Bugs Bunny communist meme is a humorous take on the character Bugs Bunny from Looney Tunes being used as a symbol of the Communist Party. The juxtaposition of a beloved cartoon character with political ideology creates a humorous and unexpected contrast, which is a common element in many internet memes. Additionally, the meme often features playful captions that subvert Bugs Bunny's typically mischievous and nonchalant attitude, further adding to the humor.",
        "formatting": '2 text captions overlaying the "Bugs bunny communist" meme.',
    },
]
