# IMGFLIP templates

MEME_VARIANTS = [
        {'id': '181913649',
  'title': 'Drake Hotline Bling',
  'explanation': '',
  'formatting': '2 text captions overlaying the Drake Hotline Bling meme.'},
 {'id': '87743020',
  'title': 'Two Buttons',
  'explanation': '',
  'formatting': '3 text captions overlaying the Two Buttons meme.'},
 {'id': '112126428',
  'title': 'Distracted Boyfriend',
  'explanation': '',
  'formatting': '3 text captions overlaying the Distracted Boyfriend meme.'},
 {'id': '217743513',
  'title': 'UNO Draw 25 Cards',
  'explanation': '',
  'formatting': '2 text captions overlaying the UNO Draw 25 Cards meme.'},
 {'id': '131087935',
  'title': 'Running Away Balloon',
  'explanation': '',
  'formatting': '5 text captions overlaying the Running Away Balloon meme.'},
 {'id': '124822590',
  'title': 'Left Exit 12 Off Ramp',
  'explanation': '',
  'formatting': '3 text captions overlaying the Left Exit 12 Off Ramp meme.'},
 {'id': '222403160',
  'title': 'Bernie I Am Once Again Asking For Your Support',
  'explanation': '',
  'formatting': '2 text captions overlaying the Bernie I Am Once Again Asking For Your Support meme.'},
 {'id': '129242436',
  'title': 'Change My Mind',
  'explanation': '',
  'formatting': '2 text captions overlaying the Change My Mind meme.'},
 {'id': '4087833',
  'title': 'Waiting Skeleton',
  'explanation': '',
  'formatting': '2 text captions overlaying the Waiting Skeleton meme.'},
 {'id': '131940431',
  'title': "Gru's Plan",
  'explanation': '',
  'formatting': "4 text captions overlaying the Gru's Plan meme."},
 {'id': '438680',
  'title': 'Batman Slapping Robin',
  'explanation': '',
  'formatting': '2 text captions overlaying the Batman Slapping Robin meme.'},
 {'id': '135256802',
  'title': 'Epic Handshake',
  'explanation': '',
  'formatting': '3 text captions overlaying the Epic Handshake meme.'},
 {'id': '80707627',
  'title': 'Sad Pablo Escobar',
  'explanation': '',
  'formatting': '3 text captions overlaying the Sad Pablo Escobar meme.'},
 {'id': '97984',
  'title': 'Disaster Girl',
  'explanation': '',
  'formatting': '2 text captions overlaying the Disaster Girl meme.'},
 {'id': '247375501',
  'title': 'Buff Doge vs. Cheems',
  'explanation': '',
  'formatting': '4 text captions overlaying the Buff Doge vs. Cheems meme.'},
 {'id': '252600902',
  'title': 'Always Has Been',
  'explanation': '',
  'formatting': '2 text captions overlaying the Always Has Been meme.'},
 {'id': '188390779',
  'title': 'Woman Yelling At Cat',
  'explanation': '',
  'formatting': '2 text captions overlaying the Woman Yelling At Cat meme.'},
 {'id': '322841258',
  'title': 'Anakin Padme 4 Panel',
  'explanation': '',
  'formatting': '3 text captions overlaying the Anakin Padme 4 Panel meme.'},
 {'id': '161865971',
  'title': 'Marked Safe From',
  'explanation': '',
  'formatting': '2 text captions overlaying the Marked Safe From meme.'},
 {'id': '91538330',
  'title': 'X, X Everywhere',
  'explanation': '',
  'formatting': '2 text captions overlaying the X, X Everywhere meme.'},
 {'id': '110163934',
  'title': "I Bet He's Thinking About Other Women",
  'explanation': '',
  'formatting': "2 text captions overlaying the I Bet He's Thinking About Other Women meme."},
 {'id': '178591752',
  'title': 'Tuxedo Winnie The Pooh',
  'explanation': '',
  'formatting': '2 text captions overlaying the Tuxedo Winnie The Pooh meme.'},
 {'id': '309868304',
  'title': 'Trade Offer',
  'explanation': '',
  'formatting': '3 text captions overlaying the Trade Offer meme.'},
 {'id': '102156234',
  'title': 'Mocking Spongebob',
  'explanation': '',
  'formatting': '2 text captions overlaying the Mocking Spongebob meme.'},
 {'id': '93895088',
  'title': 'Expanding Brain',
  'explanation': '',
  'formatting': '4 text captions overlaying the Expanding Brain meme.'},
 {'id': '79132341',
  'title': 'Bike Fall',
  'explanation': '',
  'formatting': '3 text captions overlaying the Bike Fall meme.'},
 {'id': '148909805',
  'title': 'Monkey Puppet',
  'explanation': '',
  'formatting': '2 text captions overlaying the Monkey Puppet meme.'},
 {'id': '180190441',
  'title': "They're The Same Picture",
  'explanation': '',
  'formatting': "3 text captions overlaying the They're The Same Picture meme."},
 {'id': '61579',
  'title': 'One Does Not Simply',
  'explanation': '',
  'formatting': '2 text captions overlaying the One Does Not Simply meme.'},
 {'id': '61544',
  'title': 'Success Kid',
  'explanation': '',
  'formatting': '2 text captions overlaying the Success Kid meme.'},
 {'id': '1035805',
  'title': 'Boardroom Meeting Suggestion',
  'explanation': '',
  'formatting': '4 text captions overlaying the Boardroom Meeting Suggestion meme.'},
 {'id': '101470',
  'title': 'Ancient Aliens',
  'explanation': '',
  'formatting': '2 text captions overlaying the Ancient Aliens meme.'},
 {'id': '3218037',
  'title': "This Is Where I'd Put My Trophy If I Had One",
  'explanation': '',
  'formatting': "2 text captions overlaying the This Is Where I'd Put My Trophy If I Had One meme."},
 {'id': '27813981',
  'title': 'Hide the Pain Harold',
  'explanation': '',
  'formatting': '2 text captions overlaying the Hide the Pain Harold meme.'},
 {'id': '124055727',
  'title': "Y'all Got Any More Of That",
  'explanation': '',
  'formatting': "2 text captions overlaying the Y'all Got Any More Of That meme."},
 {'id': '195515965',
  'title': 'Clown Applying Makeup',
  'explanation': '',
  'formatting': '4 text captions overlaying the Clown Applying Makeup meme.'},
 {'id': '370867422',
  'title': 'Megamind peeking',
  'explanation': '',
  'formatting': '2 text captions overlaying the Megamind peeking meme.'},
 {'id': '224015000',
  'title': 'Bernie Sanders Once Again Asking',
  'explanation': '',
  'formatting': '2 text captions overlaying the Bernie Sanders Once Again Asking meme.'},
 {'id': '55311130',
  'title': 'This Is Fine',
  'explanation': '',
  'formatting': '2 text captions overlaying the This Is Fine meme.'},
 {'id': '316466202',
  'title': 'where monkey',
  'explanation': '',
  'formatting': '2 text captions overlaying the where monkey meme.'},
 {'id': '119139145',
  'title': 'Blank Nut Button',
  'explanation': '',
  'formatting': '2 text captions overlaying the Blank Nut Button meme.'},
 {'id': '28251713',
  'title': 'Oprah You Get A',
  'explanation': '',
  'formatting': '2 text captions overlaying the Oprah You Get A meme.'},
 {'id': '100777631',
  'title': 'Is This A Pigeon',
  'explanation': '',
  'formatting': '3 text captions overlaying the Is This A Pigeon meme.'},
 {'id': '226297822',
  'title': 'Panik Kalm Panik',
  'explanation': '',
  'formatting': '3 text captions overlaying the Panik Kalm Panik meme.'},
 {'id': '252758727',
  'title': 'Mother Ignoring Kid Drowning In A Pool',
  'explanation': '',
  'formatting': '4 text captions overlaying the Mother Ignoring Kid Drowning In A Pool meme.'},
 {'id': '259237855',
  'title': 'Laughing Leo',
  'explanation': '',
  'formatting': '2 text captions overlaying the Laughing Leo meme.'},
 {'id': '509760957',
  'title': 'Travis Kelce screaming',
  'explanation': '',
  'formatting': '2 text captions overlaying the Travis Kelce screaming meme.'},
 {'id': '166969924',
  'title': 'Flex Tape',
  'explanation': '',
  'formatting': '3 text captions overlaying the Flex Tape meme.'},
 {'id': '247113703',
  'title': 'A train hitting a school bus',
  'explanation': '',
  'formatting': '2 text captions overlaying the A train hitting a school bus meme.'},
 {'id': '89370399',
  'title': 'Roll Safe Think About It',
  'explanation': '',
  'formatting': '2 text captions overlaying the Roll Safe Think About It meme.'},
 {'id': '177682295',
  'title': 'You Guys are Getting Paid',
  'explanation': '',
  'formatting': '2 text captions overlaying the You Guys are Getting Paid meme.'},
 {'id': '84341851',
  'title': 'Evil Kermit',
  'explanation': '',
  'formatting': '2 text captions overlaying the Evil Kermit meme.'},
 {'id': '99683372',
  'title': 'Sleeping Shaq',
  'explanation': '',
  'formatting': '2 text captions overlaying the Sleeping Shaq meme.'},
 {'id': '284929871',
  'title': "They don't know",
  'explanation': '',
  'formatting': "2 text captions overlaying the They don't know meme."},
 {'id': '114585149',
  'title': 'Inhaling Seagull',
  'explanation': '',
  'formatting': '4 text captions overlaying the Inhaling Seagull meme.'},
 {'id': '21735',
  'title': 'The Rock Driving',
  'explanation': '',
  'formatting': '2 text captions overlaying the The Rock Driving meme.'},
 {'id': '155067746',
  'title': 'Surprised Pikachu',
  'explanation': '',
  'formatting': '3 text captions overlaying the Surprised Pikachu meme.'},
 {'id': '134797956',
  'title': 'American Chopper Argument',
  'explanation': '',
  'formatting': '5 text captions overlaying the American Chopper Argument meme.'},
 {'id': '427308417',
  'title': '0 days without (Lenny, Simpsons)',
  'explanation': '',
  'formatting': '2 text captions overlaying the 0 days without (Lenny, Simpsons) meme.'},
 {'id': '135678846',
  'title': 'Who Killed Hannibal',
  'explanation': '',
  'formatting': '3 text captions overlaying the Who Killed Hannibal meme.'},
 {'id': '101956210',
  'title': 'Whisper and Goosebumps',
  'explanation': '',
  'formatting': '2 text captions overlaying the Whisper and Goosebumps meme.'},
 {'id': '216523697',
  'title': 'All My Homies Hate',
  'explanation': '',
  'formatting': '2 text captions overlaying the All My Homies Hate meme.'},
 {'id': '119215120',
  'title': 'Types of Headaches meme',
  'explanation': '',
  'formatting': '2 text captions overlaying the Types of Headaches meme meme.'},
 {'id': '267889046',
  'title': 'bell curve',
  'explanation': '',
  'formatting': '4 text captions overlaying the bell curve meme.'},
 {'id': '123999232',
  'title': 'The Scroll Of Truth',
  'explanation': '',
  'formatting': '2 text captions overlaying the The Scroll Of Truth meme.'},
 {'id': '6235864',
  'title': 'Finding Neverland',
  'explanation': '',
  'formatting': '3 text captions overlaying the Finding Neverland meme.'},
 {'id': '224514655',
  'title': 'Anime Girl Hiding from Terminator',
  'explanation': '',
  'formatting': '2 text captions overlaying the Anime Girl Hiding from Terminator meme.'},
 {'id': '221578498',
  'title': 'Grant Gustin over grave',
  'explanation': '',
  'formatting': '2 text captions overlaying the Grant Gustin over grave meme.'},
 {'id': '50421420',
  'title': 'Disappointed Black Guy',
  'explanation': '',
  'formatting': '2 text captions overlaying the Disappointed Black Guy meme.'},
 {'id': '101288',
  'title': 'Third World Skeptical Kid',
  'explanation': '',
  'formatting': '2 text captions overlaying the Third World Skeptical Kid meme.'},
 {'id': '77045868',
  'title': 'Pawn Stars Best I Can Do',
  'explanation': '',
  'formatting': '2 text captions overlaying the Pawn Stars Best I Can Do meme.'},
 {'id': '61556',
  'title': 'Grandma Finds The Internet',
  'explanation': '',
  'formatting': '2 text captions overlaying the Grandma Finds The Internet meme.'},
 {'id': '5496396',
  'title': 'Leonardo Dicaprio Cheers',
  'explanation': '',
  'formatting': '2 text captions overlaying the Leonardo Dicaprio Cheers meme.'},
 {'id': '171305372',
  'title': 'Soldier protecting sleeping child',
  'explanation': '',
  'formatting': '3 text captions overlaying the Soldier protecting sleeping child meme.'},
 {'id': '67452763',
  'title': 'Squidward window',
  'explanation': '',
  'formatting': '2 text captions overlaying the Squidward window meme.'},
 {'id': '234202281',
  'title': 'AJ Styles & Undertaker',
  'explanation': '',
  'formatting': '2 text captions overlaying the AJ Styles & Undertaker meme.'},
 {'id': '91998305',
  'title': 'Drake Blank',
  'explanation': '',
  'formatting': '2 text captions overlaying the Drake Blank meme.'},
 {'id': '371619279',
  'title': 'Megamind no bitches',
  'explanation': '',
  'formatting': '2 text captions overlaying the Megamind no bitches meme.'},
 {'id': '110133729',
  'title': 'spiderman pointing at spiderman',
  'explanation': '',
  'formatting': '2 text captions overlaying the spiderman pointing at spiderman meme.'},
 {'id': '61520',
  'title': 'Futurama Fry',
  'explanation': '',
  'formatting': '2 text captions overlaying the Futurama Fry meme.'},
 {'id': '360597639',
  'title': "whe i'm in a competition and my opponent is",
  'explanation': '',
  'formatting': "2 text captions overlaying the whe i'm in a competition and my opponent is meme."},
 {'id': '14371066',
  'title': 'Star Wars Yoda',
  'explanation': '',
  'formatting': '2 text captions overlaying the Star Wars Yoda meme.'},
 {'id': '175540452',
  'title': 'Unsettled Tom',
  'explanation': '',
  'formatting': '2 text captions overlaying the Unsettled Tom meme.'},
 {'id': '342785297',
  'title': 'Gus Fring we are not the same',
  'explanation': '',
  'formatting': '3 text captions overlaying the Gus Fring we are not the same meme.'},
 {'id': '29617627',
  'title': 'Look At Me',
  'explanation': '',
  'formatting': '2 text captions overlaying the Look At Me meme.'},
 {'id': '91545132',
  'title': 'Trump Bill Signing',
  'explanation': '',
  'formatting': '2 text captions overlaying the Trump Bill Signing meme.'},
 {'id': '196652226',
  'title': 'Spongebob Ight Imma Head Out',
  'explanation': '',
  'formatting': '2 text captions overlaying the Spongebob Ight Imma Head Out meme.'},
 {'id': '61532',
  'title': 'The Most Interesting Man In The World',
  'explanation': '',
  'formatting': '2 text captions overlaying the The Most Interesting Man In The World meme.'},
 {'id': '137501417',
  'title': 'Friendship ended',
  'explanation': '',
  'formatting': '2 text captions overlaying the Friendship ended meme.'},
 {'id': '187102311',
  'title': 'Three-headed Dragon',
  'explanation': '',
  'formatting': '4 text captions overlaying the Three-headed Dragon meme.'},
 {'id': '142009471',
  'title': 'is this butterfly',
  'explanation': '',
  'formatting': '3 text captions overlaying the is this butterfly meme.'},
 {'id': '177984372',
  'title': 'What Gives People Feelings of Power',
  'explanation': '',
  'formatting': '2 text captions overlaying the What Gives People Feelings of Power meme.'},
 {'id': '162372564',
  'title': 'Domino Effect',
  'explanation': '',
  'formatting': '2 text captions overlaying the Domino Effect meme.'},
 {'id': '72525473',
  'title': 'say the line bart! simpsons',
  'explanation': '',
  'formatting': '3 text captions overlaying the say the line bart! simpsons meme.'},
 {'id': '92084495',
  'title': 'Charlie Conspiracy (Always Sunny in Philidelphia)',
  'explanation': '',
  'formatting': '2 text captions overlaying the Charlie Conspiracy (Always Sunny in Philidelphia) meme.'},
 {'id': '145139900',
  'title': 'Scooby doo mask reveal',
  'explanation': '',
  'formatting': '4 text captions overlaying the Scooby doo mask reveal meme.'},
 {'id': '206151308',
  'title': 'Spider Man Triple',
  'explanation': '',
  'formatting': '3 text captions overlaying the Spider Man Triple meme.'},
 {'id': '478588645',
  'title': 'Borat 2 Tonight Queen??',
  'explanation': '',
  'formatting': '3 text captions overlaying the Borat 2 Tonight Queen?? meme.'},
 {'id': '249257686',
  'title': 'Bugs bunny communist',
  'explanation': '',
  'formatting': '2 text captions overlaying the Bugs bunny communist meme.'},
 {'id': '20007896',
  'title': "c'mon do something",
  'explanation': '',
  'formatting': "2 text captions overlaying the c'mon do something meme."}]
